services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  frontend:
    image: denoland/deno:latest
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - deno_cache:/deno-dir  # Persist Deno cache
      - node_modules:/app/node_modules # Persist node modules inside container
    environment:
      - DENO_DIR=/deno-dir  # Use the persisted cache
    depends_on:
      - backend
    entrypoint: ["/bin/sh", "-c"]
    command: ["deno task dev"]


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  deno_cache:
  node_modules:
