
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o main ."
bin = "./main"
include_ext = ["go"]
exclude_dir = ["assets", "tmp", "vendor", "frontend"]
include_dir = []
# Exclude unchanged files.
exclude_unchanged = true

log = "air.log"
# Poll files for changes instead of using fsnotify.
poll = true
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 500 # ms
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 0 # ms
# Stop running old binary when build errors occur.
stop_on_error = true


[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false
# silence all logs produced by air 
silent = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

